<?php if ($this->pageCount): ?>
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'term'=>$this->term)); ?>">
                   &laquo;
                </a></li>
        <?php else: ?>
            <li class="disabled"><span>&laquo;</span></li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url($this->route, array('page' => $page, 'term'=>$this->term)); ?>">
                        <?php echo $page; ?>
                    </a> </li>
            <?php else: ?>
                <li class="active"><span><?php echo $page; ?></span></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url($this->route, array('page' => $this->next, 'term'=>$this->term)); ?>">
                    &raquo;
                </a></li>
        <?php else: ?>
            <li class="disabled" ><span>&raquo;</span></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>